server:
  port: 10010 # 端口号
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 路由配置
        - id: userserver # 路由的id 没有固定规则但要求唯一 建议配合服务名
          uri: lb://user-server # 匹配后提供服务的路由地址 lb=LoadBalance
          predicates: # 断言 路由的条件
            - Path=/user/** # 路由断言规则 路径相匹配的进行路由
        - id: orderserver
          uri: lb://order-server
          predicates:
            - Path=/order/**
