spring:
  application:
    name: orderservice # 项目名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # 数据库驱动类
    url: jdbc:mysql://localhost:3306/db_cloud_order_server?useSSL=false&characterEncoding=utf-8 # 数据库连接地址
    username: root # 数据库用户名
    password: 123456 # 数据库密码
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址

server:
  port: 8080 # 项目端口号

logging:
  level:
    cn.surkaa: debug # 日志级别
  pattern:
    dateformat: dd HH:mm:ss:SSS # 日志时间格式

# Q: yml中如何引用上文变量
# A: ${变量名}

${spring.application.name}:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - ${spring.application.name}

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        logger-level: BASIC # feign日志级别
