server:
  # 服务端口
  port: 10001
spring:
  application:
    # 服务名称
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka的地址信息 会把自己(eureka)也注册到eureka上
      defaultZone: http://localhost:${server.port}/eureka/