server:
  port: 8080

spring:
  application:
    name: order-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_cloud_order_server
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务端地址
      discovery:
        # 是否临时实例 这将会让此服务的健康状况由nacos主动监测
        ephemeral: false

feign:
  httpclient:
    # 支持httpclient
    enabled: true
    # 连接超时时间
    connection-timeout: 5000
    # 最大连接数 连接池
    max-connections: 200
    # 单个连接的最大连接数
    max-connections-per-route: 50

#eureka:
#  client:
#    service-url:
#      # eureka服务端地址
#      defaultZone: http://localhost:10001/eureka/

mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    cn.surkaa: debug
ribbon:
  eager-load:
    # 开启饿汉模式
    enabled: true
    # 配置需要提前加载的服务
    clients: user-server
user-server:
  ribbon:
    # 配置负载均衡策略
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
