server:
  port: 8080

spring:
  application:
    name: order-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_cloud_order_server
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      # eureka服务端地址
      defaultZone: http://localhost:10001/eureka/

mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    cn.surkaa: debug